version: "3"

services:

    test:
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ./:/usr/src/app
        working_dir: /usr/src/app
        command: sh -c 'npm install; npm run start:dev'
        container_name: test
        ports:
            - "3000:3000"
        networks:
            - gateway
        environment:
            SERVICE_PORT: ${SERVICE_PORT}
            SERVICE_NAME: ${SERVICE_NAME}
            HEALTHCHECK_ID: ${HEALTHCHECK_ID}
        healthcheck:
            test: curl --fail -s https://hc-ping.com/${HEALTHCHECK_ID} || exit 1
            interval: 20s
            timeout: 10s
            retries: 3

networks:
    gateway:
