version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/build
    steps:
      - checkout

      # Install dependencies
      - run:
          name: "install dependencies"
          command: "npm install"

      # Run tests
      - run:
          name: "run tests"
          command: "npm test"

      # upload test coverage...
      - run:
          name: "upload test coverage"
          command: "bash <(curl -s https://codecov.io/bash)"
      # push image to dockerhub...
      # deploy image to digitalocean...
      # update image...
      # start new container...
