version: 2
jobs:
  build-and-test:
    docker:
      - image: circleci/node:8
    working_directory: ~/build
    steps:
      - checkout
      - run:
          name: "install dependencies"
          command: "npm install"
