version: 2
jobs:
  build:
    environment:
      IMAGE_NAME: shipyardsuite/nodejs-service-template
    docker:
      - image: circleci/node:8
      - image: mongo:3.4.4
    working_directory: ~/build
    steps:
      - checkout
      - run: npm install
  # test:
  #   docker:
  #     - image: circleci/node:8
  #   working_directory: ~/build
  #   steps:
  #     - checkout
  #     - run: npm install
  #     - run: npm test
  # build:
  #   steps:
  #     - run: echo deploying...
  # deploy:
  #   steps:
  #     - run: echo deploying...

        
workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: develop
      # - test:
      #     requires:
      #       - build